### ISSUE TITLE
Possibility of using multiple coresets

### ISSUE THREAD

**Issue by raulsoutelo** [trevorcampbell/bayesian-coresets#1]
If I understand correctly, the objective in this work is to select a coreset such that the likelihood over the parameters of the model is as close as possible to the likelihood over the parameters for the full dataset. Since MCMC requires evaluating different set of parameters many times, would it make sense to use different coresets (obtained with the same heuristic) in each evaluation? Would it reduce the bias of a single coreset? Could the same idea be used in stochastic variational inference or stochastic gradient descent? 
Thanks in advance!

**Comment by trevorcampbell** [comment]
Great question. You only need to generate one coreset -- the algorithm attempts to build a coreset that approximates the log likelihood for all parameter values in some region of high posterior mass (a Bayesian credible region). You can use the coreset in MCMC / SVI / etc -- basically, anywhere you would evaluate your log-likelihood, you can evaluate the coreset log-likelihood instead. 

The coreset construction itself (GIGA, FW, etc) is deterministic, so running it multiple times will give you the same answer. That being said, there is currently randomness in the overall pipeline (the finite projection step) -- so running the whole pipeline multiple times will give you different coresets. Combining those is not yet supported (maybe in the future!).
