### ISSUE TITLE
Labels in the Example Logistic Regression

### ISSUE THREAD

**Issue by FMZennaro** [trevorcampbell/bayesian-coresets#4]
Hey! Thanks a lot for sharing your code. I am not sure, but I was going through the simple logistic regression example and I think the code generates labels in {0,1}:

https://github.com/trevorcampbell/bayesian-coresets/blob/0480ae467ab5f340726b18377a8818080d23a6bf/examples/simple_logistic_regression/main.py#L25

which I don't think work in this form of logistic regression, instead of using labels in {-1,1} (as it is actually specified in your paper). Is it so, or did I miss something? Thanks again!

**Comment by trevorcampbell** [comment]
You're totally right. Thanks for pointing that out. I'll fix that now!
